### ISSUE TITLE
Potential generators

### ISSUE THREAD

**Issue by noamross** [ropensci/charlatan#11]
Some potential generator ideas for scientific users.  Many being convenience wrappers.

Geographic:
-   lat/long in bounds
-   place names generated by selecting location names a given type closest to lat/lon coordinates
-   Countries, U.S. states, etc.

Numeric
-    Value in range for integers and doubles
-    Values from a distribution
-    Multiple values from a multiple distribution (e.g., multivariate normal)

Categorial
-    Samples from set of categorial values
-    UUIDs

Biological
-    Gene sequences

Literature-based
-    DOIs (both real and fake/non-resolving)

**Comment by sckott** [comment]
thanks @noamross 

i think most can be done easily

**Comment by sckott** [comment]
changes in 0057a471f50896cb099491fa78f844db3545d199 adding some of the above

**Comment by sckott** [comment]
Geographic:
- [x]  lat/long in bounds
- [ ]  place names generated by selecting location names a given type closest to lat/lon coordinates - not clear what this means
- [x]  Countries, U.S. states, etc.

Numeric
- [x]  Value in range for integers and doubles
- [x]  Values from a distribution
- [ ] Multiple values from a multiple distribution (e.g., multivariate normal)  - which distribution to use?

Categorial
-  [ ]  Samples from set of categorial values - not sure what this means
-  [ ]  UUIDs - there's a cran package to do this, i guess could just import that, but maybe just point people to that if they want uuids

Biological
-  [x]  Gene sequences

Literature-based
-  [x]  DOIs (both real and fake/non-resolving)

**Comment by iembry-USGS** [comment]
I am suggesting fake data for business transactional data:

- order ID
- location ID
- Product ID
- Purchase Date
- Price Paid
- Product Type (Types of Clothing, Types of Electronics, etc.)
- Company Name - specific for industries (Clothing, Sports, Books, etc.)

Thank you.

Irucka

**Comment by sckott** [comment]
thanks @iembry-USGS - out of curiosity, would you use these for work/personal use - and just in english or other languages as well?

**Comment by iembry-USGS** [comment]
@sckott You're welcome. I would use them for work and just in English.

Thank you.

Irucka

**Comment by sckott** [comment]
thanks @iembry-USGS 

opening a new issue to discuss your ideas - continue in #52

**Comment by sckott** [comment]
closing, not sure i'll get to the other ones here
