### ISSUE TITLE
feature request: fake data for VCF format

### ISSUE THREAD

**Issue by sariya** [ropensci/charlatan#111]
Is it possible to add feature that may create data for VCf file? It is, along with all headers (# followed by other strings). We keep it to the minimal: GT, INFO, REF, ALT. 
This can be then expanded to AD (allelic depth), MAF (minor allele frequency), functional annotations (synonymous, non synonymous) and such. 
Thanks.

**Comment by sckott** [comment]
can you provide some links to examples and documentation for these vcf files?
