### ISSUE TITLE
Feature request: Add random U.S. Social Security Numbers

### ISSUE THREAD

**Issue by aalexandersson** [ropensci/charlatan#121]
Would be nice to have `charlatan` generate random U.S. Social Security Numbers (SSN).
Was commented "can do" but then removed from the v0.3 milestone in [issue 61](https://github.com/ropensci/charlatan/issues/61) in 2018.

Can possibly reuse some of the SSN code from Python library faker at 
https://github.com/joke2k/faker/blob/master/faker/providers/ssn/en_US/__init__.py

**Comment by sckott** [comment]
if you are willing, making the change yourself via a pull request would be the fastest way to get this done. what do you think?

**Comment by aalexandersson** [comment]
Scott, thank you very much for the reply. Much appreciated! I might be interested but I have not done a PR before. Is the package is still being developed? For everyone who are willing but not necessarily able, are these the required steps?

1. Fork it.
2. Clone it to your local system.
3. Make a new branch.
4. Make your changes.
5. Push it back to your repo.
6. Click the Compare & pull request button.
7. Click Create pull request to open a new pull request.

Source: [https://opensource.com/article/19/7/create-pull-request-github](https://opensource.com/article/19/7/create-pull-request-github)
Are those instructions from 2019 still correct? Or can you recommend better instructions?

**Comment by sckott** [comment]
> Is the package is still being developed? 

Sort of. I've moved on to another job so I don't get paid to work on this anymore. I try to keep it running, but ideally a new maintainer with more time will take over. 

> are these the required steps?

Yes. those are the steps!
