### ISSUE TITLE
New Maintainer Needed :-)

### ISSUE THREAD

**Issue by maelle** [ropensci/charlatan#123]
Or new maintainer team. :smile_cat: 

If you're interested, please comment in the issue.
For more info, see
- [our guidance on Changing package maintainers](https://devguide.ropensci.org/changing-maintainers.html);
- [our Package Curation Policy](https://devguide.ropensci.org/curationpolicy.html).

**Comment by RMHogervorst** [comment]
I'm interested in maintaining this package.

**Comment by maelle** [comment]
Yay! Thank you @RMHogervorst! I sent you an invitation to the organization and to a team with admin access to this repository. Note you'll need to have enabled two-factor authentication for your GitHub account if that's not already the case (see https://ropensci.org/blog/2022/05/16/requiring-2fa-for-the-ropensci-github-organization/ for context).

Please amend DESCRIPTION as soon as you get a chance.

I see you have an account in rOpenSci slack workspace but please tell me if you need an invitation to that workspace at a different email address. There's a friendly #package-maintenance channel there. You might also know our [public forum](https://discuss.ropensci.org/). And ping me for any question!

**Comment by RMHogervorst** [comment]
Thank you! I will change the description today and pick other things up this monday. Thanks!

**Comment by RMHogervorst** [comment]
@maelle I am in the ropensci slack workspace, but I see only the random and general channels, no others.

**Comment by maelle** [comment]
Thanks again @RMHogervorst! Noting we've now solved the Slack issue :relieved:
