### ISSUE TITLE
[DE] Some `company-provider` entries are doubled

### ISSUE THREAD

**Issue by patperu** [ropensci/charlatan#45]
Some entries in `company-provider-de_DE.R` occur multiple times (e.g. "GmbH", "AG", "KG")

**Comment by sckott** [comment]
thanks @patperu - will have a look

**Comment by sckott** [comment]
sorry i haven't gotten around to this. looking at it now, and i just copied this from the python library. DO you think there's any chance the duplicated entries are to indicate that they are more common, so that they will be more often selected? Or is that not the case in German?

**Comment by patperu** [comment]
Ahh, I see! Yes, they are quite common.

**Comment by sckott** [comment]
so you think we should retain those duplicates IF they indicate that the duplicated names are more common?

**Comment by RMHogervorst** [comment]
Feel free to reopen this issue if the duplication is not wanted
