### ISSUE TITLE
fake business transactional data

### ISSUE THREAD

**Issue by sckott** [ropensci/charlatan#52]
via #11 | @iembry-USGS

Thoughts/questions on your list of items:

- order ID, location ID, Product ID: _what kinds of IDs ?_
- Purchase Date: _already handled, using this pkg, or easy to do yourself too_
- Price Paid: _these would just be random numbers > 0, yes?_
- Product Type (Types of Clothing, Types of Electronics, etc.): _can you give examples?_
- Company Name - specific for industries (Clothing, Sports, Books, etc.): _we do already have a company name generator, does it do what you need?_

**Comment by iembry-USGS** [comment]
@sckott  I have enclosed various examples below:

Examples of order ID
- 6831
- IK021C3
- 1IOQ
- 3490210421


Examples of location ID
- KY092
- LAR
- 78BY


Examples of Product ID [Stock Keeping Unit (SKU)]
- 59673
- 8928317183718374137483
- 34348491BLJN
- 893BLT


Price Paid
US dollar transactions ranging from $0.01 to $999,999,999.99 (It would be ideal to have the transactions to make sense. For example, a car price of $0.10 would not make sense nor a basketball for $1,023.98.)

Examples of Product Type (Types of Clothing, Types of Electronics, etc.)
- Types of Clothing

1. Shoes
        Dress shoes
	Tennis shoes
	Boots
		Hiking boots
		Country & Western style boots
2. Jeans
	Regular fit
	Straight fit
3. Dresses
	Summer dress
	Evening gown
4. Socks
	Dress socks
5. Belts


- Types of Electronics
1. Cellular phone
2. Television
3. Laptop Computer
4. Modem
5. Speakers
6. DVD Drive
7. Printer
8. Microphone

- Company Name - I have used the company name generator, but the names are generic and not specifically tied to an industry or specialization.

1. Clothing
Barbara's Women's Clothing & Shoes
Clothing Smart
Urban Trending Wear
Steve's Men's Clothing & Shoes
Big & Tall Clothing Outlet
Everyday Clothiers

2. Sports
Soccer Enthusiast
All Sports Outlet
Sportmania
US Footballers Place
Basket Ballers

3. Books
The Bookery
Book Outlet
Science Fiction Bookstore

Thank you.

Irucka

**Comment by sckott** [comment]
thanks @iembry-USGS

**Comment by iembry-USGS** [comment]
@sckott You're very welcome. Please let me know if you need anything else from me.

Irucka
