### ISSUE TITLE
Mention related packages in the docs?

### ISSUE THREAD

**Issue by maelle** [ropensci/charlatan#72]
E.g. https://www.jstatsoft.org/article/view/v074i11 h/t https://twitter.com/DanyX23/status/976418431053549569

**Comment by sckott** [comment]
thanks @maelle

**Comment by isteves** [comment]
I've been dealing with this problem recently as I write puzzles, and I've come across the following related packages in the process:

https://github.com/trinker/wakefield
https://github.com/richfitz/ids
https://github.com/gaborcsardi/rcorpora

Hope that helps!
