### ISSUE TITLE
Julia package Faker might have some useful features?

### ISSUE THREAD

**Issue by njtierney** [ropensci/charlatan#74]
Heya! 

Feel free to disregard this, but I found this Julia package, `Faker`, thought some of its functionality might be of interest: https://github.com/codeneomatrix/Faker.jl

**Comment by sckott** [comment]
👋 nice, have looked at python and ruby versions, but hadn't seen that. 

are there particular functionalities you'd be interested in?

**Comment by njtierney** [comment]
👋 

Not as yet actually, I haven't needed to make a fake dataset for a little while, but that might change soon! I'll let you know if they crop up. :)

**Comment by sckott** [comment]
Okay. I'll have a look and see what we can bring over here

**Comment by sckott** [comment]
dont see anything new in the julia pkg
