### ISSUE TITLE
Max Number of unique CC_service_providers possible and the possibility of specifying unique factor levels and distribute that to the large data vector

### ISSUE THREAD

**Issue by ammubharatram** [ropensci/charlatan#99]
Hi, firstly thanks for the cool package in R. I have used the function 'ch_credit_card_provider' to create 5 million entries of banks. Using the glimpse statement from dplyr in R, I could see that almost all the first 10 entries are either Mastercard or JCB 16 digit (PFA [image](https://www.dropbox.com/s/kjzsccgb8yjnamt/Charlatan.PNG?dl=0))  I wonder now how many unique fake credit card providers has this package got? And also is it possible to specify the  distribution of the names (at least something like distribute 1.5 million names to 5 million entries randomly) so that sequential entries don't get the same provider so frequently, as seems in this case? Thanks in advance!

**Comment by sckott** [comment]
thanks for your question @ammubharatram 

it looks like we have 10 unique providers https://github.com/ropensci/charlatan/blob/master/R/credit_card-provider.R#L33-L44  Are there more that we could add?  

> is it possible to specify the distribution of the names ...

it is already random. by chance you may get many in sequence that are the same. Would it work for your use case to run `ch_credit_card_provider()` and then re-shuffle them?

**Comment by ammubharatram** [comment]
Thanks Scott for your quick reply and also for the R code which mention the 10 uniq providers. I guess reshuffling them should do the trick ,thanks for the idea. 
 I then checked for the ‘name.R’ code as I also used ch_name. However, I can’t see the number of uniq names used nor could I recognize the source for them. Could you please answer that as well? Thanks in advance!

Regards,
Bharat Ram Ammu,
Data Scientist,
Complidata,
Belgium.

**Comment by sckott** [comment]
`ch_name` uses `PersonProvider` https://github.com/ropensci/charlatan/blob/master/R/person-provider.R - it depends on which locale you use for this one - look at all the files in https://github.com/ropensci/charlatan/tree/master/R and see which locale you'd use

**Comment by ammubharatram** [comment]
Got it, seems like around 200 names from what I see. Thanks for the quick help and for the cool package and wish you both good luck for expanding this to larger scale applications!

Regards,
Bharat Ram Ammu,
Data Scientist,
Complidata,
Belgium.

**Comment by sckott** [comment]
glad you find it useful, thanks for your questions
